export const SPIED_SHOTS = 6
export const SPIED_ENEMY = 3
export const SHOT_SIZE = 3
export const PLAYER_SCALE = 0.15
export const BONUS_OUTER_RADIUS = 10
export const BONUS_INNER_RADIUS = 5
export const BONUS_SPIKES = 5
export const BONUS_BORDER_WIDTH = 5
export const BONUS_TIME = 4000
export const BONUS_COLOR = 'skyblue'
export const BONUS_BORDER_COLOR = 'blue'
export const REWORD_FOR_KILLED_ENEMY = 25
export const FREQUENCY_APPEAR_ENEMY = 1250
export const FREQUENCY_GUN_SHOT = 5
export const FREQUENCY_ENEMY_SHOT = 360
export const FREQUENCY_APPEAR_BONUS = 3000
export const FPS = 60
export const PLAYER_SPED = 2
export const POINT_ANIMATION_DURATION = 1500
export const ENEMY_TYPE_STATIC = 'STATIC'
export const ENEMY_TYPE_TRACKING = 'TRACKING'
export const ENEMY_TYPE_SPINNING =  'SPINNING'
export const ENEMY_TYPE_SPINNING_TRACKING = 'SPINNING_TRACKING'

export const xCenter: number = document.body.clientWidth / 2
export const yCenter: number = window.innerHeight / 2
export const yBottom: number = window.innerHeight

export const rgbRegex = /[.\d]+/g;